#+TITLE: About
#+DESCRIPTION: 80% Scientist, 20% Artist. Theorist and practitioner.
#+AUTHOR: Aaron Kuehler
#+OPTIONS: num:nil toc:nil

#+BEGIN_QUOTE
Always remember, our purpose is not to "write code", but rather add value.
#+END_QUOTE

Hi, I'm Aaron.

I'm a Software Developer with almost 20 years of professional
experience delivering value, and impacting users and teammates alike.

Professionally, my expertise lies in software development and building
technical teams. I embarked on my journey in Computer Science and
Computer Programming in 1999. Since then, I have dedicated myself to
continually enhancing my knowledge in these areas to excel in my
professional endeavors.

Software development is so much more than instructing a machine how to
solve a problem. Effective human collaboration is as important as
elegant technical design in order to build truly impactful solutions.
Therefore, I prioritize understanding human behavior, fostering honest
communication and relationships, and developing leadership skills and
honing purely technical skills equally.

Personally, I possess a diverse range of interests; including being a
father, musician, home brewer, soap maker, woodworker, pre-industrial
hand tool refurbisher, photographer, and electronics tinkerer. I have
a passion for learning and creating.

* Open Source Contributions

** Shopify/shipit-engine

https://github.com/Shopify/shipit-engine

Shipit is a deployment tool that makes shipping code better for
everyone. It's especially great for large teams of developers and
designers who work together to build and deploy GitHub repos.

** percona-xtradb-cluster-operator

https://github.com/indiebrain/percona-xtradb-cluster-operator

A Kubernetes operator for Percona XtraDB Cluster based on the Operator
SDK.
** rubyforgood/mutual-aid

https://github.com/rubyforgood/mutual-aid

Mutual Aid is when people get together to build community by volunarily
sharing resources with each other. Mutual Aid groups are more concerned
about local resiliency than global campaigns, and prefer solidarity
before charity.

** k9s

https://github.com/derailed/k9s

K9s provides a terminal UI to interact with your Kubernetes clusters.
The aim of this project is to make it easier to navigate, observe and
manage your applications in the wild. K9s continually watches Kubernetes
for changes and offers subsequent commands to interact with your
observed resources.

** Shopify/krane

https://github.com/Shopify/krane

krane is a command line tool that helps you ship changes to a Kubernetes
namespace and understand the result.

** heroku-cli-buildpack

https://github.com/Thermondo/heroku-cli-buildpack

Installs the Heroku toolbelt on a heroku dyno.

** Keyword Parameter Matchers

https://github.com/terryfinn/keyword_parameter_matchers

RSpec matchers for method keyword parameters.

** githug

https://github.com/Gazler/githug

Githug is designed to give you a practical way of learning git. It has a
series of levels, each requiring you to use git commands to arrive at a
correct answer.

* Side Projects

** asdf-guile

https://github.com/indiebrain/asdf-guile

An [[https://github.com/asdf-vm/asdf][asdf]] version manager plugin to manage [[https://www.gnu.org/software/guile/][GNU Guile]] installations

** futurist

https://github.com/indiebrain/futurist

An implementation of the future construct, inspired by Celluloid's block
based futures, which uses process forking as a means of backgrounding
work.

** backbone-elasticsearch

https://github.com/indiebrain/backbone-elasticsearch

Adapters and Utilities to interface Backbone.js with ElasticSearch

** OmniAuth Doximity OAuth2

https://github.com/indiebrain/omniauth-doximity_oauth2

A Doximity OAuth2 Strategy for OmniAuth.

* Elsewhere

  - https://www.linkedin.com/in/aaronkuehler
  - https://www.github.com/indiebrain
