#+TITLE: About
#+DESCRIPTION: 80% Scientist, 20% Artist. Theorist and practitioner.
#+AUTHOR: Aaron Kuehler
#+OPTIONS: num:nil

I write software for fun and profit. I like creating. I like delivering. Shipping maintainable software that helps people makes me happy. I believe in developing software confidently. I prefer to define automated specifications of system behavior before I write implementation. I prefer to build features from the outside-in-- starting with the highest level of interaction and working my way down. I believe in using the right tools for the right job. I believe it is better to be a problem solver than a <%= popular technology %> expert. I believe that interpersonal skills are a requisite part of a development toolbox. Effective communication, conflict resolution, self and team awareness are as essential to success as a solid technical foundation. I enjoy working in collaborative environments and function best on small, cross-functional teams.


* OSS Contributions

** heroku-buildpack-cli

   https://github.com/Thermondo/heroku-buildpack-cli

   Installs the Heroku toolbelt on a heroku dyno.

** Githug

   https://github.com/Gazler/githug

   Githug is designed to give you a practical way of learning git. It has a series of levels, each requiring you to use git commands to arrive at a correct answer.

** Keyword Parameter Matchers

   https://github.com/indiebrain/keyword_parameter_matchers

   Simple matchers for method keyword parameters.

* Side Projects

** Futurist

   https://github.com/indiebrain/futurist

   An implementation of the future construct, inspired by Celluloid's block based futures, which uses process forking as a means of backgrounding work.

** Backbone-Elasticsearch

   https://github.com/indiebrain/backbone-elasticsearch

   Adapters and Utilities to interface Backbone.js with ElasticSearch

** OmniAuth Doximity OAuth2

   https://github.com/indiebrain/omniauth-doximity_oauth2

   A Doximity OAuth2 Strategy for OmniAuth.

* Elsewhere

  - https://www.linkedin.com/in/aaronkuehler
  - https://www.twitter.com/indiebrain
  - https://www.github.com/indiebrain
