#+TITLE: About
#+DESCRIPTION: 80% Scientist, 20% Artist. Theorist and practitioner.
#+AUTHOR: Aaron Kuehler
#+OPTIONS: num:nil toc:nil

#+BEGIN_QUOTE
Our purpose is not to "write code", but rather add value.
#+END_QUOTE

Over 15 years of experience shipping software and growing development teams. I thrive in collaborative environments where impact is celebrated.

* Example Open Source Contributions

** Shopify/shipit-engine

https://github.com/Shopify/shipit-engine

Shipit is a deployment tool that makes shipping code better for
everyone. It's especially great for large teams of developers and
designers who work together to build and deploy GitHub repos.

** percona-xtradb-cluster-operator

https://github.com/indiebrain/percona-xtradb-cluster-operator

A Kubernetes operator for Percona XtraDB Cluster based on the Operator
SDK.
** rubyforgood/mutual-aid

https://github.com/rubyforgood/mutual-aid

Mutual Aid is when people get together to build community by volunarily
sharing resources with each other. Mutual Aid groups are more concerned
about local resiliency than global campaigns, and prefer solidarity
before charity.

* Sample Side Projects

** asdf-guile

https://github.com/indiebrain/asdf-guile

An [[https://github.com/asdf-vm/asdf][asdf]] version manager plugin to manage [[https://www.gnu.org/software/guile/][GNU Guile]] installations

** rescue-alive

https://github.com/indiebrain/resque-alive

A Kubernetes Liveness probe for Resque

* Elsewhere

- https://www.github.com/indiebrain
- https://www.linkedin.com/in/aaronkuehler/
