#+TITLE:       Aaron Kuehler
#+AUTHOR:
#+DATE:
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: Professional information of Aaron Kuehler
#+OPTIONS: texht:t
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [10pt letterpaper notitlepage]
#+LATEX_HEADER: \pagenumbering{gobble}
#+LATEX_HEADER: \usepackage{helvet}
#+LATEX_HEADER: \renewcommand{\familydefault}{phv}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usepackage[left=1.25cm,right=1.25cm,top=1.5cm,bottom=1.5cm,columnsep=1.2cm]{geometry}
#+LATEX_HEADER: \usepackage{enumitem}
#+LATEX_HEADER: \setlist[itemize]{label=$\circ$,itemsep=-5pt}

Over 15 years of experience developing software, mentoring, and
delivering value thorugh a wide range of software solutions including
monolithic web applications, distributed systems, and deployment
pipeline and developer tooling. I thrive in collaborative environments
where sharing and learning from our unique experience is valued, and
where impact is celebrated.

* Proficiency highlights

- Web Application / API Development: Ruby, Rails, HTTP, React, JavaScript, CSS, REST, GraphQL
- Development Tooling: Bash, Ruby
- Containerization and orchestration: podman, Docker, Kubernetes
- Team Growth and Leadership: Agility, Lean Manufacturing Principles, Extreme Ownership
- Mentorship and Education

* Recent Experience

** Shopify

*Senior Software Developer* /September 2021 - May 2023/

- Led integration of Shopify Fulfillment Network Returns and Deliverr.
- Led load testing, disaster drills, and risk mitigation for Shopify Fulfillment Network Returns processing during 2022's "Black Friday / Cyber Monday".
- Implemented Product-level Taxonomy and categorization capabilities to enhance Warehouse Operational efficiency.
- Implemented progressive feature gating, progressive rollout, and management capabilities.
- Performed on-call and maintenance shifts to ensure smooth operation of software and warehouse operations for customers.
- Mentored interns and early career developers; supporting their professional growth.
- Delivered talks on Ruby "gotchas" found in the code base.

** exercism.io

*Volunteer Mentor* /August 2019 - September 2021/

- Supported students in Ruby and Emacs-Lisp tracks by providing exercise evaluation and mentoring.

** Power Home Remodeling Group

*Senior Software Developer / Substitute Instructor / Mentor* /May 2018 - September 2021/

- Developed software delivery pipeline tooling using Jenkins CI, Docker, Shopify/shipit-engine, Shopify/krane, and Kubernetes.
- Contributed upstream enhancements to Shopify/shipit-engine, including "Review Stacks" ([[https://github.com/Shopify/shipit-engine/pull/1102][https://github.com/Shopify/shipit-engine/pull/1102]]), "Custom task execution strategies" ([[https://github.com/Shopify/shipit-engine/pull/1107][https://github.com/Shopify/shipit-engine/pull/1107]]), and "Fix: corrupt git caches cause tasks to 'exit status 128'" ([[https://github.com/Shopify/shipit-engine/pull/1169][https://github.com/Shopify/shipit-engine/pull/1169]]).
- Managed planning and commitment ceremonies for the "Release Engineering" team.
- Developed tooling to streamline onboarding and enhance the quality of life for development teams.
- Maintained and evolved a 10+ year old "Component based Rails Application" (https://cbra.info).
- Integrated "Business Intelligence" visualization using JavaScript (ES6).
- Supported telephony applications using Asterisk (PBX) / SIP.

** Bauer Xcel Media

*Technical Team Lead / Senior Software Developer* /February 2016 - May 2018/

- Developed home-grown, multi-tenant, publishing, and sweepstakes Rails applications.
- Optimized content presentation for maximum SEO relevance.
- Developed the team's operational support competence and distributed knowledge by creating the "On-call / incident response playbook."
- Introduced process monitoring metrics, resulting in a 34.4% reduction in cycle time.
- Developed an automated "Review Application" workflow, leading to a 50% decrease in monthly development team hosting costs.

** Sizmek (formerly PointRoll) :noexport:

*Software Developer* /January 2015 - June 2016/

- Developed targeted video advertising platform using VAST XML delivery standards.
- Mentored team through transition to an agility-based software process.
- Supported business through acquisition to eventual project shuttering while maintaining services for clients such as Apple, Jaguar, and BMW.

** Hoopla :noexport:

*Software Developer* /July 2012 - January 2015/

- Developed Hoopla platform, a Rails application for sales team motivation.
- Maintained Salesforce integration, an Apex-based communication bridge between Salesforce Orgs and Hoopla metrics and events APIs.
- Developed "Hoopla TV," a web-based sales SportsCenter-esque UI over the Hoopla platform to display sales metrics and events.
- Provided exceptional support to large-account customers, including LinkedIn, Zillow, Angie's List, and Ring Central.
- Led Mobile API development team and later assumed responsibility for native mobile application development.

** Artisan (formerly AppRenaissance) :noexport:

*Senior Software Developer* /July 2011 - July 2012/

- Developed and deployed native iOS applications to the App Store for clients, including Chinoki, Trustlines, and Interact.
- Built consulting business from 2 developers to a product team of 10 in less than a year.

** Infor :noexport:

*Software Engineer* /May 2009 - July 2011/

- Developed "Orders and Requisitions" and "Accounts Payable" components of the Enterprise Resource Planning system.
- Founded the "Brown-Bag" club to promote cross-team relationship building and knowledge sharing.

** Oracle (formerly AdminServer) :noexport:

*Application Engineer* /February 2006 - June 2009/

- Developed data-driven Life and Annuity insurance policy administration system.
- Led research and development for next-gen offerings.
- Led development team to incorporate R&D findings into product evolution.

* Sample Open Source Contributions

** Shopify/shipit-engine

https://github.com/Shopify/shipit-engine

Shipit is a deployment tool that makes shipping code better for everyone. It's especially great for large teams of developers and designers who work together to build and deploy GitHub repos.

** percona-xtradb-cluster-operator

https://github.com/indiebrain/percona-xtradb-cluster-operator

A Kubernetes operator for Percona XtraDB Cluster based on the Operator SDK.

** rubyforgood/mutual-aid

https://github.com/rubyforgood/mutual-aid

Mutual Aid is when people get together to build community by volunarily sharing resources with each other. Mutual Aid groups are more concerned about local resiliency than global campaigns, and prefer solidarity before charity.

* Sample Side Projects

** asdf-guile

https://github.com/indiebrain/asdf-guile

An [[https://github.com/asdf-vm/asdf][asdf]] version manager plugin to manage [[https://www.gnu.org/software/guile/][GNU Guile]] installations

** rescue-alive

https://github.com/indiebrain/resque-alive

A Kubernetes Liveness probe for Resque

** futurist

https://github.com/indiebrain/futurist

An implementation of the future construct, inspired by Celluloid's block based futures, which uses process forking as a means of backgrounding work.

* Talks

** Git Internals

https://github.com/indiebrain/talks/blob/master/git_internals/git_internals.org

A talk on the inner workings of git and its influence on the user interface.

* Education

** West Chester University of Pennsylvania

*Bachelor of Science, Computer Science with Information Assurance Minor*

/January 2006/

- Magna Cum Laude
- Award for Academic Excellence (2006)
- Dean's list (2005 and 2006)

* Research

** Small File Affects on Hadoop Distributed File System

- [[https://raw.githubusercontent.com/indiebrain/indiebrain.github.io/source/resume/small-file-affects-on-hadoop-distributed-file-sytem.pdf][Whitepaper PDF]]

An discussion of the impact of small files on Hadoop Distributed File System, proposing mitigation techniques.

* Elsewhere

- https://aaronkuehler.com
- https://www.github.com/indiebrain
- https://www.linkedin.com/in/aaronkuehler/
