#+TITLE:       Aaron Kuehler
#+AUTHOR:
#+DATE:
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: Professional information of Aaron Kuehler
#+OPTIONS: texht:t
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [12pt letterpaper notitlepage]
#+LATEX_HEADER: \pagenumbering{gobble}
#+LATEX_HEADER: \usepackage{helvet}
#+LATEX_HEADER: \renewcommand{\familydefault}{phv}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usepackage[margin=0.75in]{geometry}

#+BEGIN_QUOTE
Over 15 years of experience shipping software and growing development
teams. I thrive in collaborative environments where impact is
celebrated.
#+END_QUOTE

* Proficiency highlights

- Web Application Development (Ruby/Rails and Standard Web
  Technologies - HTTP, JavaScript, CSS)
- API Development (Ruby/Rails)
- Development tooling, Continuous Integration, Deployment Automation,
  and Workload Orchestration (Bash, Jenkins, Docker, Kubernetes)
- Team Growth and Leadership (agility, Lean Manufacturing Principles,
  and Extreme Ownership)
- Mentor and Educator

* Recent Accomplishments

** Shopify

*Senior Software Developer*

/September 2021 - May 2023/

Shipped the $2.5 billion USD acquisition / integration of Deliverr Inc
ahead of schedule. Ensured alignment of our geographically diverse
team. Defined APIs and implemented the Shopify integration to ensure
seamless experience for SFN merchants.

Increased Returns system throughput by 500% ahead of the SFN Returns
2022 Black Friday / Cyber Monday season. Ran capacity and resilience
testing to identify choke-points. Led disaster recovery drills and
defined on-call and incident response policies.

Discovered silent failure modes in warehouse management software and
added observably instrumentation. Discovered impediments in warehouse
processes and implemented optimizations with AI-based inventory
categorizations.

Identified bottlenecks in feature gating system. Scaled feature flag
management capabilities from 10 to 2 million merchants. Added
percentage-based feature rollouts, feature lifecycle automation,
enhanced human-consumable feature metadata.

Grew 2 interns into autonomous Individual Contributors in weeks
through pairing, synchronous 1:1 support, and defining right-sized
work items.

** Power Home Remodeling Group

*Senior Software Developer / Substitute Instructor / Mentor*

/May 2018 - September 2021/

Slashed deployment times by 82%. Transformed deployment topology to
self-hosted Kubernetes-based container orchestration. Made significant
contributions to [[https://github.com/Shopify/shipit-engine/pulls?q=author%3Aindiebrain][Shopify/shipit-engine]] to support Review Stacks.

Improved call center reliability by 300% by identifying constrained
resources, decoupling and distributing the telephony system by call
type.

Expanded development organization capacity by 20% by growing "Power
Code Academy" student developers into Individual Contributors.
Functioned as a substitute instructor and post-graduation mentor.

** Bauer Xcel Media

*Technical Team Lead / Senior Software Developer*

/February 2016 - May 2018/

Boosted revenue by 200% by optimizing impression value and advertising
rank. Deferred ad load requests until ad slots were just about to
scroll into reader's view.

Cut development organization spend by 50%. Implemented automated
review instances to share WIP with stakeholders.

Reduced work-item cycle-time by 34.37% by encouraging adoption of
pairing and building a [[https://aaronkuehler.com/blog/2019/05/09/building-a-healthy-code-review-culture/][healthy code review culture]].

Increased site traffic by 300% by optimizing metadata for search
engine and social media ranking.

** exercism.io

*Volunteer Mentor*

/August 2019 - September 2021/


Mentored over 60 students along the Ruby and Emacs-Lisp language
tracks.

* Extended work history :noexport:
** Sizmek (formerly PointRoll)

*Software Developer*

/January 2015 - June 2016/

** Hoopla

*Software Developer*

/July 2012 - January 2015/

** Artisan (formerly AppRenaissance)

*Senior Software Developer*

/July 2011 - July 2012/

** Infor

*Software Engineer*

/May 2009 - July 2011/

** Oracle (formerly AdminServer)

*Application Engineer*

/February 2006 - June 2009/

* Example Open Source Contributions

** Shopify/shipit-engine

https://github.com/Shopify/shipit-engine

Shipit is a deployment tool that makes shipping code better for
everyone. It's especially great for large teams of developers and
designers who work together to build and deploy GitHub repos.

** percona-xtradb-cluster-operator

https://github.com/indiebrain/percona-xtradb-cluster-operator

A Kubernetes operator for Percona XtraDB Cluster based on the Operator
SDK.

** rubyforgood/mutual-aid

https://github.com/rubyforgood/mutual-aid

Mutual Aid is when people get together to build community by voluntarily
sharing resources with each other. Mutual Aid groups are more concerned
about local resiliency than global campaigns, and prefer solidarity
before charity.

* Sample Side Projects

** asdf-guile

https://github.com/indiebrain/asdf-guile

An [[https://github.com/asdf-vm/asdf][asdf]] version manager plugin to manage [[https://www.gnu.org/software/guile/][GNU Guile]] installations

** rescue-alive

https://github.com/indiebrain/resque-alive

A Kubernetes Liveness probe for Resque

** futurist :noexport:

https://github.com/indiebrain/futurist

An implementation of the future construct, inspired by Celluloid's block
based futures, which uses process forking as a means of backgrounding
work.

** backbone-elasticsearch :noexport:

https://github.com/indiebrain/backbone-elasticsearch

Adapters and Utilities to interface Backbone.js with ElasticSearch

** OmniAuth Doximity OAuth2 :noexport:

https://github.com/indiebrain/omniauth-doximity_oauth2

An OmniAuth (https://github.com/intridea/omniauth) OAuth2 strategy for
Doximity (http://www.doximity.com/)

* Talks

** Git Internals

https://github.com/indiebrain/talks/blob/master/git_internals/git_internals.org

Explains the inner workings of git and sheds a bit of light on
how the internal structure of git as a data store influences its user
interface.

* Elsewhere

- https://aaronkuehler.com
- https://www.github.com/indiebrain
- https://www.linkedin.com/in/aaronkuehler/

* Education

** West Chester University of Pennsylvania

*Bachelor of Science, Computer Science with Information Assurance Minor*

/January 2006/

- Magna Cum Laude
- Award for Academic Excellence (2006)
- Dean's list (2005 and 2006)

*** Research

**** Small File Affects on Hadoop Distributed File System

- [[https://raw.githubusercontent.com/indiebrain/indiebrain.github.io/source/resume/small-file-affects-on-hadoop-distributed-file-sytem.pdf][Whitepaper PDF]]

The Hadoop Distributed File System is a high throughput distributed File
system designed to accommodate large data sets; average file sizes in
the gigabyte-terabyte range. However when a data set is composed of
large amounts of small files, say in the kilobyte range, the storage
system's semantics introduce height amounts of overhead in terms of file
system block storage and read latency. This paper explains the
architectural attributes which cause these problems and examines
techniques to mitigate their impact when working with data sets
comprised of large numbers of small files.
