#+TITLE:       Design Effective Interviews
#+AUTHOR:      Aaron Kuehler
#+DATE:        2015-05-14 Thu
#+URI:         /blog/%y/%m/%d/design-effective-interviews
#+KEYWORDS:    hiring, interviewing, team building
#+TAGS:        hiring, team building
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: Effective hiring strategies to build successful teams

Conducting an interview is difficult. How well can you expect to know someone after a few hours of interaction? This is why it's important to optimize the time spent speaking with a candidate. I've conducted interviews for a variety of roles: Software Developers, Customer Support Representatives, Development Managers. I've had the opporunity to speak with dozens of candidates. I've made my fair share of mistakes -- asked the wrong questions, pressed a topic too hard, or lacked significant information or preparation to conducting the interview. Each interview provides an opporunity for me to hone my skills and better understand the responsibility -- to company and candidate -- of an interviewer.

This article is an exploration of the essence of practicing meaningful interviewing.

*TL;DR;*

- Core competencies
  + Hard Skills - Aptitude and Technical Knowledge
  + Soft Skills - Interpersonal Communication and Emotional Intelligence
- Three things a successful interview will answer - Never ask these directly, ask for historical examples, look for patterns to support the candidate's claims
  + Can the candidate do the job?
  + Do I believe that the environment would be enhanced by having the candidate on board?
  + Do I believe that the candidate would be happy working in the environment?

* Core Competencies

** Hard Skills

   Hard skills are the candidates relevant technical knowledge, intellectual proficiency, and aptitudes directly related to the mechanics of the role for which the candidate is being considered. For example, a Software Development candidate's degree of familiarity with a particular language or software development methodology used at your company is an interesting Hard Skill. A candidate's propensity for logical reasoning and gaining new knowledge is also an interesting Hard Skill.

** Soft Skills

   Soft skills typically refer to non-technical intelligence and knowledge which help the candidate navigate the human aspects of the workplace; self-awareness, interpersonal communication, conflict resolution, leadership and mentoring techniques, learning styles, and the like. The best way to seek answers to these types of questions is to ask candidates for concrete examples of their behavior or experience in previous situations and look for patterns of conduct. Most candidates find this line of questioning difficult; I suspect because most interviews put so much emphasis on Hard Skills. Soft skills interviews are best conducted with questions that point the candidate in a direction, but are open ended enough to serve as stepping off points for deeper conversations.

#+BEGIN_QUOTE
Tell me about a time when you were part of a successful team; what were the top 3 traits of the team which caused it to be successful?
#+END_QUOTE

* The Things You Really Want To Know

  Early on, I struggled as an interviewer because I wasn't really sure what I needed to know about a candidate -- if you were unfortunate enough to be one of these candidates, I'm sorry and I promise I'm trying to get better. I would ask leading questions and get very similar answers from most candidates or I would ask dead end, filler questions that didn't give me anything useful, didn't lead anywhere, or even worse I didn't really care about the answer. I quickly learned that the essence of a good interview aims at answering three basic questions which you will never ever want to ask a candidate directly.

** Can the candidate do the job?

   Keep the technical questions relevant to topics the candidate might encounter frequently in the role for which their interviewing.

   Hard Skills questioning can go awry for a few, related, reasons. First, the topics are irrelevant to the work expected of the candidate. If you're not making use of the Gateway Pattern, don't ask about the Gateway Pattern. Anything the candidate offers up is fair game, but be a filter and redirect the conversation to relevant topics. Second, I consider it an interview smell when emphasis is placed on Whiteboard Code exercises. The artificial setting and power dynamics of the interview environment tend to affect the outcomes of these exerciese in significant ways. Instead, ask for a collection of sample code from a candidate ahead of time and review their work in the interview. Ask about the problems the candidate encountered that led them to choose their particular architectures and technologies.

#+BEGIN_QUOTE
Your work history mentions you have experience with Distributed Systems at ACME Corporation, can you describe for me the problem you were trying to solve, draw an architecture diagram, and let's discuss how your work fit into the solution?
#+END_QUOTE

** Do I believe that the environment would be enhanced by having the candidate on board?

   Try to determine how the candidate will affect the culture of the company and happiness of their coworkers. Focus on the candidate's ability and awareness of managing relationships and communication. Particular attention should be given to how the candidate's styles mesh with the zeitgeist of the organization: processes, business conditions, practices, and values of the organization. Typically, I might collect examples of the candidate's experience mentoring, being mentored, how they've handled conflict or communicating uncomfortable information to a coworker, personality traits that have helped them succeed or stumble.

** Do I believe that the candidate would be happy working in the environment?

   Being on the inside of an organization and having the opportunity to dig deep on the needs, goals, and aspirations of a candidate gives the interviewer a particularly powerful and important position in determining if a candidate will thrive. The interviewer should probe about the candidate's experience working in conditions similar to those of the organization and gain a understand the conditions and constraints of the organization are ones in which the candidate will be happy, productive, and fulfilled.

   For example, a few years ago I worked on a small, highly collaborative team. We were open about the strengths and weaknesses of each member and we leaned on each other to meet our commitments. Our motto was "All of us are better than any of us"; we valued the team over individuals. As our product gained traction we needed to grow our team. We asked a lot of questions about candidate experience working as part of a team. One particularly troublesome candidate answered our first team oriented question with:

#+BEGIN_QUOTE
I work better by myself. I like it when I can get all of my work done and no one has to bother me.
#+END_QUOTE

   For obvious reasons, this candidates would have been unsuccessful in our organization so we decided to not extend them an offer. Importantly, we were honest about why we didn't feel that the candidate was a good fit and parted ways on good terms. In the long run, we hired candidates who shared our values and the new hires were happy and productive.

* Some Closing Pieces of Advice

This article only explains the motivations for the questions I actually ask in interviews rather than enumerating a list of questions actually asked in interviews -- here's the secret, they change from interview to interview. It's best to have a few high-level Conversation Starter questions that take you to interesting places with your candidate rather than trying to script the interview.

Keep in mind that the best interviews are a conversation, not a chess match; don't try to outwit the candidate. The interview is as much for the candidate to understand how your organization behaves, the problems they're likely to encounter, etc as it is for you to make a judgement call about if they'd be a good fit for the role and organization. Be truthful about The Good, The Bad, and The Ugly of your organization and what the candidate should expect in their role.

Always place higher value on concrete examples from the candidate's history over hypotheticals. It's easy to say that you want to, or would, do the right thing to a hypothetical. Ask for real examples to establish patterns of behavior. Candidates, often times, don't know how they behave, but patterns explain quite a bit about who we are and what motivates us.

Be compassionate and merciful. Interviews are a contrived, high stress environment where, traditionally, the interviewer holds a power advantage; you're the gatekeeper to the next step of employment for the candidate. Comfortable candidates offer the most truths. Non-verbal communication is an excellent way to set a positive tone to the conversation. Sitting next to or standing at the whiteboard with the candidate, posturing in and engaging direct eye contact  when the candidate speaks can go a long way to opening up the space for deeper conversation.

As an interviewer, you will encounter people who come from all kinds of backgrounds. Know your biases and be aware how they might affect your judgement. Collect as many objective data points to answer the above 3 questions and make the most educated decision about a candidate you can given the information you were able to obtain during your interview.

Remember the 6Ps: *Proper Planning and Practice Prevent Poor Performance*. Recognize that you are human. No matter how much you practice, occasionally, you will mess up. Never miss an opportunity to run an interview; after each, reflect on and adapt your technique.
